### ISSUE TITLE
ModuleNotFoundError: No module named 'cpupower_gui'

### ISSUE THREAD

**Issue by coreybruce** [vagnum08/cpupower-gui#1]
Xubuntu 18.04 LTS

Traceback (most recent call last):
  File "./cpupower-gui", line 34, in <module>
    from cpupower_gui import __main__
ModuleNotFoundError: No module named 'cpupower_gui'

**Comment by vagnum08** [comment]
There is a built package for Ubuntu 18.04 on [Launchpad](https://code.launchpad.net/~erigas/+archive/ubuntu/cpupower-gui).

You can add the ppa and install cpupower-gui. It should work.

In the meantime I will try to resolve the issue if the module is not found at the expected path.

**Comment by coreybruce** [comment]
No I built from source and installed the dependencies sorry, Ah well that's fantastic news! I added the PPA and installed it and everything is working thanks!

If anyone does want to install from source you might want to fix this so they can tho I am much happier adding a PPA and installing it :)
