### ISSUE TITLE
OBS link

### ISSUE THREAD

**Issue by edogawa23** [vagnum08/cpupower-gui#104]
Would you mind changing your links to OBS packages to point at multimedia:proaudio, not home:erigas, and possibly adding a paragraph for openSUSE? The commands would be as stated in 
https://software.opensuse.org//download.html?project=multimedia%3Aproaudio&package=cpupower-gui
(under section "add repo and install manually").
cpupower-gui isn't directly related to pro audio but we use itt to switch to performance mode when aiming for xrun-free audio from Ardour etc. I've branched and unlinked our package from home:erigas one, in fact the one in home:erigas is a branch of ours now, and currently unfortunately is broken after yesterday's package update in our repo which seems to have introduced untrackable changes to the spec file(we ran a tool called spec-cleaner that updates and checks for common errors and deprecated stuff). This needs fixing or branching anew from erigas.

**Comment by edogawa23** [comment]
I see...
I think I identified and fixed the packaging bug, by removing the polkit rules.d directory ownership for Fedora. 

I have built a test version for Fedora 36 in my home project in OBS: 
https://software.opensuse.org//download.html?project=home%3Aedogawa&package=cpupower-gui

Anyways, looking forward to seeing a new release.

**Comment by edogawa23** [comment]
Just to mention, after a month and no feedback from fedora users, I now submitted my modifications to the more permanent GeekosDAW repo and enabled building and publishing for Fedora 36 - 38.

**Comment by vagnum08** [comment]
I will change the README to point to GeekosDAW repo for OpenSUSE and Fedora packages.

**Comment by vagnum08** [comment]
Took me a while but it is done now. I live-booted to Fedora 38, grabbed your package from OBS and it worked without any fuss. I also noticed that you built the package from latest git commit. That helps with the previous bugs for meson, etc.
