### ISSUE TITLE
Frequency setting reset after reboot.

### ISSUE THREAD

**Issue by lb-d** [vagnum08/cpupower-gui#13]
I'm running Ubuntu 20.04 beta and the frequency I set in cpupower-gui reset after a reboot/shutdown. Before I found this amazing program I use to set frequency manually in a terminal in /sys/device/system/cpu/cpu*/cpufreq/scaling_max_frequency and that also resets after a reboot so it's the system and not your program I believe.

**Comment by vagnum08** [comment]
Hi,
This is not a bug. The changes applied to `sysfs` are temporary.
To retain the settings after reboot a daemon has to run during boot-up and apply the settings automatically.

I planned on implementing this for a long time. Now with the pandemic, I will have some spare time to finally implement this feature.

**Comment by lb-d** [comment]
Nice. I just added cpup-g to autostart, so not the biggest deal really.

**Comment by LemonadeG** [comment]
> Hi,
> This is not a bug. The changes applied to `sysfs` are temporary.
> To retain the settings after reboot a daemon has to run during boot-up and apply the settings automatically.
> 
> I planned on implementing this for a long time. Now with the pandemic, I will have some spare time to finally implement this feature.

Any news on this? Thanks in advance!

**Comment by vagnum08** [comment]
Hopefully in the next two weeks.

**Comment by PDXUser** [comment]
Any updates on the auto setting after reboot?

**Comment by vagnum08** [comment]
I haven't worked on it for a while. However, I thought it was a good opportunity to additionally add user profiles which you can quickly switch to. 

I plan to work on it in October and make some updates.

**Comment by vagnum08** [comment]
If have issues setting up the configuration and the profiles let me know.

**Comment by Intaria** [comment]
+
