### ISSUE TITLE
A way to see available frequencies?

### ISSUE THREAD

**Issue by lb-d** [vagnum08/cpupower-gui#14]
I set frenquencies as recommended in   /sys/device/system/cpu/cpu*/cpufreq/scaling_available_frequencies and did the same when I ran tlp as reported with the command  sudo tlp-stat -p

Or does it make any difference if I follow those recommended frequencies or just chose something else?

Anyway. Great program :)

**Comment by vagnum08** [comment]
> Anyway. Great program :)

Thanks.
To answer your question.

### Short answer
You can set the frequencies to any value in that range. You don't have to set it to the ones specified by `scaling_available_frequencies`.

### Long answer

These are frequency steps as reported by `cpupower`. If you look in `/sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq` or in current CPU frequency reported by `cpupower` you will see that the frequency can take any value in that range.  There is caveat though.

Some systems do not have `scaling_available_frequencies` (I have seen it on intel cpus). On those systems you can set the frequency limits to any value over the operating range.

However, for systems that do have `scaling_available_frequencies`, the frequency limits have a constraint.
To illustrate the constraint, assume that you have the following available frequency steps:  3.50 GHz, 3.00 GHz, 2.20 GHz.

If you set minimum limit to be 2.20 GHz you can set the maximum limit to any value from 2.20 GHz to 3.50 GHz.
On the other hand if you set the maximum limit to 3.50 GHz you can set the minimum to any value in that range. 

The caveat I mentioned earlier, is that if you change the minimum limit inside a step range (e.g. 2.20 to 3.00 GHz) then the maximum limit will be set to the top of that step range.
However, you don't have to do this manually; if need be the system will adjust the frequency limits values automatically as you can see below.
![cpg_step](https://user-images.githubusercontent.com/16070176/79335201-83c72d80-7f19-11ea-8143-f729d9fa9024.gif)

**Comment by lb-d** [comment]
I see. I only set the max frequency to keep my thinkpad from getting to hot.  Thanks for the good explanation.
