### ISSUE TITLE
0.8.0 not available in apt

### ISSUE THREAD

**Issue by saikat0511** [vagnum08/cpupower-gui#15]

**Comment by vagnum08** [comment]
Hi,

First, which distro (and version) are you using?

The latest debian package is on mentors ([here](https://mentors.debian.net/package/cpupower-gui)) but hasn't picked up yet.


There should be  Debian and Ubuntu repos available on OBS, but there seems to be an issue with that. I will have a look why that is the case.

**Comment by vagnum08** [comment]
Sorry for taking that long.

You can find the binaries for 0.8.0 at opensuse's build service repo.
Here is the link for the repo
https://software.opensuse.org/download.html?project=home%3Aerigas%3Acpupower-gui&package=cpupower-gui 

You can either add the repo (following the instruction on the site) or download the debian (.deb) package and installing directly.

The opensuse repository will be updated with the newer versions of cpupower-gui.
