### ISSUE TITLE
Error due to the version of python3 and its module 

### ISSUE THREAD

**Issue by jiangzc** [vagnum08/cpupower-gui#16]
My Python version is 3.5.3 and the following syntax is not supported. Hope to replace it with  compatible statement.

https://github.com/vagnum08/cpupower-gui/blob/23d95af0f8f342a9236005b5119ec58385b57f6a/cpupower_gui/cpupower-gui-helper.py.in#L126

I also have this issue : AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'  
https://github.com/tuhiproject/tuhi/issues/197
It seems that module PyGObject version should be greater than 3.30 .

You can note these dependency issue in README file.   Thanks.

**Comment by vagnum08** [comment]
Thanks for letting me know.

After this commit https://github.com/vagnum08/cpupower-gui/commit/e3fb852d2ac90b9fc79609abe68b9140df78af56, PyGObject version should be greater than 3.30.
There is an error message generated by the following line.
https://github.com/vagnum08/cpupower-gui/blob/23d95af0f8f342a9236005b5119ec58385b57f6a/cpupower_gui/main.py#L24

I will add a note to README about the version.

**Comment by vagnum08** [comment]
I have removed the f-string from the print statement. Now it should work. The changes have been merged.
