### ISSUE TITLE
Enable all available governors

### ISSUE THREAD

**Issue by testsieger73** [vagnum08/cpupower-gui#20]
**Is your feature request related to a problem? Please describe.**
A It is possible to choose between 2 governors, schedutil and performance (AMD Zen 2 CPU). However, the governors ondemand, powersave, conservative and userspace are not available.

**Describe the solution you'd like**
A I would like to be able to choose all available governors in the drop down menu.

**Describe alternatives you've considered**
A Activating one of these governors via command line (e.g. `cpupower frequency-set -g powersave`), makes the governor show up in the drop down menu. To make them all show up, they all have to be activated via command line first.

**Additional context**
-

**Comment by vagnum08** [comment]
Thanks for the suggestion. It sounds good. I will work on it in the next few days.

**Comment by vagnum08** [comment]
I did some testing. Apparently it doesn't work with every CPU. I think the easiest way to do it and preserve it across reboots is to enable the kernel modules using a config file in `/etc/modules-load.d/`.

I will add a config file to the project with all the kernel modules. To enable you will have to copy the file over to that location. 

So, a `cp /usr/share/cpupower-gui/enable-all-governors.conf /etc/modules-load.d/enable-all-governors.conf` will be all needed to enable all them at boot automatically.

**Comment by avalonv** [comment]
Was this actually implemented afterall? I have only two scaling governors available, and I can't seem to find that file.

**Comment by avalonv** [comment]
My mistake, I didn't notice that the file is now called `scaling-governors.conf`. However, having copied it to `/etc/modules-load.d/` and rebooted, those governors still aren't available. Should I open a new issue?

**Comment by vagnum08** [comment]
Which distro are you using?

**Comment by avalonv** [comment]
Arch linux
