### ISSUE TITLE
Configurable default settings

### ISSUE THREAD

**Issue by unode** [vagnum08/cpupower-gui#24]
I would like to have the "All CPUs" switch on by default.

Is there any config file or setting that can be defined to allow this?

Thanks

**Comment by vagnum08** [comment]
The changes are merged, and would be included on the next release that would be available soon.
To enable it, just change` allcpus_default=False` to `allcpus_default=True`.
Either in `~/.config/cpupower_gui/99-allcpus.conf` or `/etc/cpupower-gui.conf`.

**Comment by unode** [comment]
Thanks for such a quick implementation!
