### ISSUE TITLE
polkit cpupower-gui.rules are not installed

### ISSUE THREAD

**Issue by unode** [vagnum08/cpupower-gui#28]
While packaging cpupower-gui for NixOS I had to [manually copy the `cpupower-gui.rules` file](https://github.com/NixOS/nixpkgs/blob/24430347588f5ff37e8044a775fd43b2e9e39945/pkgs/os-specific/linux/cpupower/gui.nix#L61) from the source directory in order to allow `wheel` members to modify settings without `sudo`.
I noticed that this file is not installed. Is this intended behaviour?

**Comment by vagnum08** [comment]
Not exactly. It depends on the distro. Debian still uses `PolicyKit`, which relies on the `.pkla` files. Up till now the default was to package these over the rules file, and have rules be copied manually.

I was thinking about it recently, and considering adding a switch in meson to control the behaviour.
Probably I will go with `.rules` being the default and the switch will be used for Debian and derivatives.

**Comment by vagnum08** [comment]
Tested it on Arch and it works with the default options.
However, I added the `install -d ...` line as without it the permissions of the folder is `755` instead of `750`.
