### ISSUE TITLE
Display current CPU frequency

### ISSUE THREAD

**Issue by unode** [vagnum08/cpupower-gui#32]
Occasionally I notice that my system slows down despite reasonable min/max frequency settings.
A few times I've realized this is caused by the CPU being forced into a lower frequency due to thermal throttling or some other reason.

Would it be possible to include a `Current Frequency` display in cpupower-gui?

This information is shown in `cpupower frequency-info`:
```
# cpupower frequency-info
analyzing CPU 0:
(...)
  current CPU frequency: Unable to call hardware
  current CPU frequency: 800 MHz (asserted by call to kernel)     <-------------
(...)
```

As frequency changes rather often, this panel would have to refresh constantly.

**Comment by vagnum08** [comment]
Sort answer: I am planning to add this.

Long answer:

On the `treew-view` branch I am adding a table with the settings. The plan is to also add the current CPU frequency.

Here is a preview as it is now d009be9
![2020-10-16-003134](https://user-images.githubusercontent.com/16070176/96253357-5d0eb000-0fab-11eb-9e31-00209716e93d.png)

**Comment by unode** [comment]
The table in the screenshot looks great. Looking forward to that update.

**Comment by vagnum08** [comment]
I changed the UI and the current scaling frequency is displayed in the table. It has an updates every 500ms.

**Comment by unode** [comment]
This looks great, massive thanks!
I'll also be finishing the nixOS packaging this weekend.

**Comment by vagnum08** [comment]
I plan to release a new version this weekend.
