### ISSUE TITLE
Rendering is cut off for frequency

### ISSUE THREAD

**Issue by PDXUser** [vagnum08/cpupower-gui#33]
I am using KDE 5.20.0 in Arch using the default Breeze theme and color sets.

![Screenshot_20201016_073710](https://user-images.githubusercontent.com/20736534/96272067-751e0980-0f82-11eb-95b9-c05b0014346a.png)

As you can see in the image, the numbers in the CPU frequency are cut off.    It is most evident with the 0 number a the end. 

Also, the bottom profile box is out of alignment and cut off by the window.

**Comment by vagnum08** [comment]
I will look into it. It has something to do with the margins.

It depends on the theme, too.

For example, with Adwaita theme:

![view](https://raw.githubusercontent.com/vagnum08/cpupower-gui/media/screenshots/default_view.png)

Or with Arc Dark:
![2020-10-16-200649](https://user-images.githubusercontent.com/16070176/96298933-2c4e6b00-0feb-11eb-849b-4abf3758fd2b.png)
