### ISSUE TITLE
Problem with the GUI

### ISSUE THREAD

**Issue by AlfredEVOL** [vagnum08/cpupower-gui#37]
Font colors are off in core number

Also , some commands are missing as well

 - PopOS 20.10
 - cpupower-gui 0.9.1
 - Installed via: source

![Screenshot from 2020-10-29 06-58-59](https://user-images.githubusercontent.com/57448041/97514358-815b8b00-19b4-11eb-93e1-85d04518e1e0.png)

![Screenshot from 2020-10-29 07-04-21](https://user-images.githubusercontent.com/57448041/97514576-165e8400-19b5-11eb-9e20-d43bc697535e.png)

**P.S:** the package in Pop Shop was last updated on September of 2019...please do something about it

**Comment by vagnum08** [comment]
Hi,

- For the colour in the core number, I will try to fix it in the next few days.
- For the missing commands, these are the ones for energy performance, they are Intel specific and you have to use the `intel_pstate` driver too.
- For the package, I now it is old but I am trying to find a sponsor for the package to upload it to Debian. Then, all the other distributions based on Debian/Ubuntu will have the package a couple of days later.

**Comment by vagnum08** [comment]
Yes, I would add the commands.

**Comment by vagnum08** [comment]
The changes are in master since 9e23938.
