### ISSUE TITLE
authorization is checked only once

### ISSUE THREAD

**Issue by lindi2** [vagnum08/cpupower-gui#4]
_is_authorized checks authorization of a sender only once if the authorization succeeds. This prevents me from restricting CPU frequency changes only to active users. I guess this is bit theoretical but a user could do the following:

1. Login to the system
2. Connect to the system bus and call some method of the cpupower-gui service that calls _is_authorized. Since the user is active self.authorized[sender] gets populated.
3. Lock the screen or even log out completely but leave the dbus client running.
4. Wait for some other user to log in.
5. Start annoying the locally logged-in user by slowing down the system :)

Similarly if you for example require the user to be in some group (wheel in the example), I cannot just remove the user from the group since the authorization is not checked for each call. This is something that policykit was specifically designed to fix afaik (typically group changes required logout/login).

**Comment by vagnum08** [comment]
Interesting. I will remove the caching of the authorisation.

Initially, I added  `subject.isInGroup ("wheel")` in the policy file for the case where if two users are connected on the system, it will require the user who wants to alter the frequency to be active and an admin.

@lindi2: Do you think that `subject.local` and `subject.active` should be enough to grant access to change the frequency at runtime. After all the have access to the machine.

**Comment by lindi2** [comment]
I guess that depends on what the use case for changing the CPU frequency is? Maybe in the beginning it would be a good default to require an admin. However, I don't think you should assume anything about the wheel group. At least on my debian 9 system I am not part of that group but I can e.g. change the partition layout with udisks if I enter the root password.

**Comment by vagnum08** [comment]
I had a look yesterday, and the policykit rules  in Debian use the sudo group. Also, since Debian uses policykit < 0.105 it requires `.pkla` files instead of `.rules`. My plan is to have to rules for the action. One for active users in the sudo group (since most PC user are also sudoers on their system) and a second rule for the rest of the active users if the pass the auth_admin check.
