### ISSUE TITLE
Governor column value fails to update when governor is changed outside of the GUI

### ISSUE THREAD

**Issue by zelifcam** [vagnum08/cpupower-gui#43]
**Describe the bug**
When using the app "cpupower-gui"  CPU, Online, Min, Max, Governor and Current freq, display normally.  If the user changes the profile using the command line, the GUI does not detect the change except for the "Current freq." column.  Every other column remains with old values.

**To Reproduce**
Steps to reproduce the behaviour:
1. OPEN cpupower-gui and take note of the values in the Governor column
2. SWITCH to a terminal run "cpupower-gui -p" or "cpupower-gui -b"
3. MONITOR the Governor column on the cpupower-gui app
4. NOTICE all values remain unchanged except for the "Current freq." column.

**Expected behaviour**
Cpupower-gui should update ALL columns when changes to CPU governors happen outside of using the gui app.

**Setup (please complete the following information):**
 - Distro: Manjaro
 - Package version: 1.0.0 -2
 - Installed via: AUR
 - Kernel:  5.10.0-1-MANJARO
 - Processor: AMD Ryzen 9 5950X 16-Core Processor
 
**Additional context**
NA

**Comment by zelifcam** [comment]
Reset button on the top left solves the problem.  Would be nice to see it auto refresh maybe every 5-10 seconds, but the built in solution works.

**Comment by vagnum08** [comment]
Auto refresh sounds good. I will add it in the next release.
