### ISSUE TITLE
Can't install on Deepin

### ISSUE THREAD

**Issue by vesterlay** [vagnum08/cpupower-gui#47]
Hello, I wonder if there is a way to install this app on Deepin? Build requires `meson.build:1:0: ERROR:  Meson version is 0.49.2 but project requires >= 0.50.0.` and I can't find anything in repositories..

**Comment by vagnum08** [comment]
Sorry for the late response. I had a quick look and it seems that the latest version of meson is 0.49.

**Comment by vesterlay** [comment]
At first I wanted to install using this instruction: 
```
echo 'deb http://download.opensuse.org/repositories/home:/erigas:/cpupower-gui/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:erigas:cpupower-gui.list
curl -fsSL https://download.opensuse.org/repositories/home:erigas:cpupower-gui/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:erigas:cpupower-gui.gpg > /dev/null
```
however it failed due to lack of SSL.

I managed to update meson through .deb file from deb repo and everything went smoothly later on.
I guess this issue can be closed.
