### ISSUE TITLE
[Linux Mint 20] Adding the repo causes apt to refuse to update from it

### ISSUE THREAD

**Issue by GingkathFox** [vagnum08/cpupower-gui#49]
**Describe the bug**
APT refuses to update from `http://download.opensuse.org/repositories/home:/erigas:/cpupower-gui/xUbuntu_20.04/`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow install instructions
2. Run `apt update`
3. View output

**Expected behaviour**
Apt doesn't complain.

**Actual behavior**
```
W: No Hash entry in Release file /var/lib/apt/lists/partial/download.opensuse.org_repositories_home:_erigas:_cpupower-gui_xUbuntu%5f20.04_InRelease
E: The repository 'http://download.opensuse.org/repositories/home:/erigas:/cpupower-gui/xUbuntu_20.04  InRelease' provides only weak security information.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Setup (please complete the following information):**
 - Distro: Linux Mint
 - Package version: N/A
 - Installed via: `apt`

**Comment by vagnum08** [comment]
You might have to edit the apt rules file to allow less secure settings for the cpupowergui repository.

**Comment by GingkathFox** [comment]
Hm, i guess it decided to work. new issue, opening different issue
