### ISSUE TITLE
not working now

### ISSUE THREAD

**Issue by EdLovecraft** [vagnum08/cpupower-gui#6]
```
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 34, in <module>
    from cpupower_gui import __main__
ModuleNotFoundError: No module named 'cpupower_gui'

```

**Comment by vagnum08** [comment]
This usually happens when python is updated to a new version making the module unaccesible.
Which distro are you using? Did you install it from source or a package?

**Comment by vagnum08** [comment]
With #7 this error should never happen.
To resolve the issue now you can do the following,
Either rebuild the package or reinstall.
