### ISSUE TITLE
Fedora 34 cpupower-gui build

### ISSUE THREAD

**Issue by mrdeepmind** [vagnum08/cpupower-gui#67]
Hello! I've been using cpupower-gui for a long time. I just wanted  to ask that is there a plan to build new release cpupower-gui for Fedora34? You know we use Fedora33 build and it has some issues also that I will create issue later on. Even with version difference, it's working great (with some minor issues)

**Comment by vagnum08** [comment]
Hi, it is on my plans to update the build but I am on a busy schedule. Hopefully in a week or two.

**Comment by mrdeepmind** [comment]
You are awesome!

**Comment by vagnum08** [comment]
There is a repo for Fedora 34 on OBS now. You can have a go at it.

N.B. I haven't tested the package yet. But it should work without any issues.

**Comment by mrdeepmind** [comment]
I moved to Arch. Things have changed in my mind. :> 

https://aur.archlinux.org/packages/cpupower-gui/
