### ISSUE TITLE
Failure meson build

### ISSUE THREAD

**Issue by wavy-baby** [vagnum08/cpupower-gui#71]
Can not build properly using yay

I get this error message:
cpupower-gui-1.0.0/data/meson.build:14:0: ERROR: Function does not take positional arguments.

Here is the full log:
Build started at 2021-10-27T19:26:03.710799
Main binary: /usr/bin/python
Build Options: -Dsystemddir=/usr/lib/systemd -Dprefix=/usr -Dbuildtype=plain
Python system: Linux
The Meson build system
Version: 0.60.0
Source dir: /home/michael/.cache/yay/cpupower-gui/src/cpupower-gui-1.0.0
Build dir: /home/michael/.cache/yay/cpupower-gui/src/build
Build type: native build
Project name: cpupower-gui
Project version: 1.0.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Configuring cpupower-gui using configuration
Configuring cpupower-gui-helper using configuration
Configuring window.ui using configuration
Pkg-config binary for MachineChoice.BUILD is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.70.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
-L/usr/lib -lglib-2.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
-lglib-2.0
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring org.rnd2.cpupower_gui.desktop.in using configuration

cpupower-gui-1.0.0/data/meson.build:14:0: ERROR: Function does not take positional arguments.

When trying to build manual same error, heres the log;

Build started at 2021-10-29T00:12:53.781969
Main binary: /usr/bin/python
Build Options: -Dsystemddir=/usr/lib/systemd -Dpkla=false -Duse_libexec=false -Dprefix=/usr
Python system: Linux
The Meson build system
Version: 0.60.0
Source dir: /home/michael/cpupower-gui
Build dir: /home/michael/cpupower-gui/build
Build type: native build
Project name: cpupower-gui
Project version: 1.0.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Configuring cpupower-gui using configuration
Configuring cpupower-gui-helper using configuration
Configuring window.ui using configuration
Pkg-config binary for MachineChoice.BUILD is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.70.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
-L/usr/lib -lglib-2.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
-lglib-2.0
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring org.rnd2.cpupower_gui.desktop.in using configuration

data/meson.build:14:0: ERROR: Function does not take positional arguments.

**Comment by vagnum08** [comment]
Cannot troubleshoot it at the moment. I will try to troubleshoot it the following week.

**Comment by vagnum08** [comment]
It seems to have an issue with the configuration of the desktop file.

**Comment by wavy-baby** [comment]
> It seems to have an issue with the configuration of the desktop file.

How to fix it?

**Comment by wavy-baby** [comment]
> Seems quite odd that this issue got closed without it being fixed.

On Nov 8, 2021I tried to build it again and it worked so I closed the issue
