### ISSUE TITLE
Frequency automatically gets reset after being applied

### ISSUE THREAD

**Issue by rdgh8** [vagnum08/cpupower-gui#74]
**Describe the bug**

On my AMD Ryzen 7 5700U, any change I make to the frequency with the sliders is immediately reset after applying. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Change frequency using sliders
2. Apply
3. Notice that it gets reset

**Expected behaviour**

Allow frequency to be changed, or display the change properly if it is being applied

**Setup (please complete the following information):**
 - Distro: Ubuntu 21.10
 - Package version: 1.0.0
 - Installed via: source

**Additional context**

The frequency shown by the Current freq. column as well as `cat \proc\cpuinfo | grep MHz` is higher than the max frequency shown by the slider, although the two do not match each other for some reason. 

https://user-images.githubusercontent.com/66289396/147895178-27a4da8e-d373-4f4c-850e-18780ec11542.mp4

**Comment by vagnum08** [comment]
Hey,

I took another look at it and I noticed something.

On the video above, if you pause after you applied the setting you can notice that the frequencies of some CPU cores m are above 1800MHz, some are around 4000.

I noticed the U on 5700, so this is a laptop CPU. I have a Ryzen 5 desktop CPU and doesn't show this behaviour.

This made me think, probably the maximum base frequency is 1.8GHz and 4.3GHz might be a boosted one.

Based on Wikipedia[1] my assumption is correct. It seems you can only set a maximum of 1.8GHz and let the CPU boost on its own.  There is no way (probably) to set it to 4.3GHz for all cores.

[1] https://en.wikipedia.org/wiki/List_of_AMD_Ryzen_processors#Lucienne_(5000_series)
