### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by timofeika** [vagnum08/cpupower-gui#75]
Cannot build, got an error (meson)

this is exactly the same bug as described here: https://github.com/vagnum08/cpupower-gui/issues/71

**Comment by vagnum08** [comment]
i18n.merge_file had been ignoring positional arguments but since meson 0.60.0 it explicitly rejects it.

If you remove line 15 from cpupower-gui/data/meson.build that says 'desktop' , it should work.

**Comment by vagnum08** [comment]
Removed the offending line from meson.build in master.
