### ISSUE TITLE
It won't launch

### ISSUE THREAD

**Issue by Samaykom1** [vagnum08/cpupower-gui#83]
Cpupower-gui won't launch on lubuntu 20.04.4 lts

**Comment by vagnum08** [comment]
Check if you have `gir1.2-handy-1` installed.

**Comment by vagnum08** [comment]
I guess that `handy-1` won't be on the repos.

You can install them by downloading the following packages from ubuntu archive:
http://archive.ubuntu.com/ubuntu/pool/main/libh/libhandy-1/gir1.2-handy-1_1.2.3-1_amd64.deb
http://archive.ubuntu.com/ubuntu/pool/main/libh/libhandy-1/libhandy-1-0_1.2.3-1_amd64.deb
