### ISSUE TITLE
After first run, cpupower-gui can't retreive the CPU frequency, main GUI stops showing up

### ISSUE THREAD

**Issue by Absolutia** [vagnum08/cpupower-gui#88]
**Describe the bug**
cpupower-gui can't retrieve the CPU frequency, so the main GUI never shows up.

**To Reproduce**
Install on Manjaro, launch it, maybe change some settings (ie turn off a few logical processors), close the window and restart the app. The GUI won't show up again.

**Expected behaviour**
Looking back on it I should assume that the GUI would appear on application startup, and the output on my terminal seems to imply that it is trying, but is failing because the OS won't let it read it. Running as root doesn't change that.

**Setup (please complete the following information):**
 - Distro: Manjaro GNU/Linux
 - Package version: 1.0.0-5
 - Installed via: AUR via Trizen

**Additional context**
What leads me to think it has something to do with the CPU frequency?
`WARNING! Unknown CPU frequency, cause: [Errno 16] Device or resource busy`
Then my terminal prints this traceback: [https://pastebin.com/UC5bFvFr](url)

I have a Ryzen 7 2700X in my machine and `cpupower` (non gui) complains that it is unable to call the hardware (but is able to retrieve it from the kernel) so I'm gonna go out on a limb and say the issues are related somehow. Definitely isn't my hardware though because I have an Ubuntu Budgie 20.4 installation on another hard disk and `cpupower-gui` runs just fine, if I'm remembering correctly.

Originally this was a bug report for something I thought was a bug in the tray UI, specifically a missing feature or something not registering correctly. Whatever is causing this its definitely not the tray UI, but it would still be nice to have a restore button in there.

**Comment by Absolutia** [comment]
It appears my suspicions were correct. It can't retrieve the CPU frequency, so the main GUI never shows up.
`WARNING! Unknown CPU frequency, cause: [Errno 16] Device or resource busy`

This makes little sense because it started earlier with no problems.

**Comment by vagnum08** [comment]
It might be the kernel version you have installed. It won't be the first time where the buggy kernel doesn't report CPU frequencies causing cpupower and gui to fail.

**Comment by vagnum08** [comment]
Can you boot to previous version and check if it works?

**Comment by Absolutia** [comment]
Well, I'm not sure what I was expecting but I changed to kernel version 5.15.60 and it works as it should.

Running `cpupower frequency-info` and it still complains about it being "unable to call hardware" so whatever is causing that is definitely unrelated...
