### ISSUE TITLE
Build instructions do not reflect switch to meson

### ISSUE THREAD

**Issue by ksteimel** [vagnum08/cpupower-gui#9]
**Is your feature request related to a problem? Please describe.**
The build instructions in the README are for the old bulld system using autoconf not the new build system using meson and ninja.

**Describe the solution you'd like**
I would like instructions for building using meson (though I expect they follow the conventional meson workflow).

**Additional context**
The errors I'm getting with install may be due to me using meson incorrectly so this will allow me to determine the cause.

**Comment by vagnum08** [comment]
I have updated the README with instruction for building the package with meson.
Give it a try and if you have any issues building or installing let me know.
Which distro are you using by the way?

**Comment by ksteimel** [comment]
I'm using opensuse tumbleweed. Do you know if this is compatible with KDE? I get errors on launch like that shown below: 

```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.rnd2.cpupower_gui.helper': timed out (service_start_timeout=25000ms)
```

**Comment by vagnum08** [comment]
From what I see it looks like there is a problem with the dbus service and probably its installed location.

I had previously tried to package for opensuse but had missing build dependencies. Now with meson it might be fine.

I will let you know soon.

**Comment by vagnum08** [comment]
I got it working on a live tumbleweed KDE CD. 

The problem was that the default prefix is /usr/local and dbus services cannot be started from local.

I have updated the README to use the correct prefix and added info for openSUSE.
 
There will be a package on OBS soon.

**Comment by ksteimel** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Oh rad! Thank you very much!                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: December 11, 2019 12:56 PMTo: cpupower-gui@noreply.github.comReply-to: reply@reply.github.comCc: ksteimel@iu.edu; author@noreply.github.comSubject: [External] Re: [vagnum08/cpupower-gui] Build instructions do not reflect switch to meson (#9)  This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.I got it working on a live tumbleweed KDE CD.
The problem was that the default prefix is /usr/local and dbus services cannot be started from local.
I have updated the README to use the correct prefix and added info for openSUSE.
There will be a package on OBS soon.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vagnum08** [comment]
The package is on OBS (link on readme).
