### ISSUE TITLE
governor Powersave does not exist 

### ISSUE THREAD

**Issue by WillSilvah** [vagnum08/cpupower-gui#94]
In the options to select a governor, there are no governors "powersave", "userspace" and the like, It only has "schedutil" and "performance" only.
In Lubuntu 22.04 it had everything, conservative, userspace, conservative, performance and all 

Now I'm on Debian 11 and it doesn't have

**Comment by vagnum08** [comment]
There is a configuration file in the data folder.
You can read here https://github.com/vagnum08/cpupower-gui#enabling-extra-governors, on how to enable the extra governors using that file.

Let me know if you have any issues with that.
