### ISSUE TITLE
Fix OBS link and fedora 37 support

### ISSUE THREAD

**Issue by LeSnake04** [vagnum08/cpupower-gui#95]
**Is your feature request related to a problem? Please describe.**
The current repo link in the readme is invalid and all packages on OBS are only for fedora 36

**Describe the solution you'd like**
Please link a official build for fedora 37

**Additional context**
This program looks like a good replacement for the gnome extension "cpu power manager" which doesnt have gnome 43 support yet, so an up to date official fedora repo would be great.

**Comment by vagnum08** [comment]
I just logged-in to OBS and the cpupower-gui repository was removed 5 days ago. It doesn't say why it was removed though.

I will have to make a new repo I guess.

**Comment by careca1970** [comment]
Hi!
Noticed that package couldn't be updated by DNF anymore, since a week or so.
Please, rebuild the repository.

Many thanks for the good work!  :+1:

**Comment by ninoorta** [comment]
I still get errors with Fedora 37, any updates on this ?

**Comment by LeSnake04** [comment]
I found a working package: https://copr.fedorainfracloud.org/coprs/phantomx/chinforpms/package/cpupower-gui/

Thugh i dont recommend the repo and just download the rpm instead.

**Comment by vagnum08** [comment]
I have updated the OBS link in README. You can install cpupower-gui from the this repo https://software.opensuse.org//download.html?project=multimedia%3Aproaudio&package=cpupower-gui

It has the latest version from master, not the latest release (which is a bit dated).
